/*
 * ettercap2c.c - Convert the 'ettercap' passive OS fingerprint database
 *                file to a C variable to be included in programs
 *
 * -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 *                    _        _
 *              _ __ | | _____| |__
 *             | '_ \| |/ / __| '_ \
 *             | |_) |   <\__ \ | | |
 *             | .__/|_|\_\___/_| |_|
 *             |_|
 *
 *            'pksh', the Packet Shell
 *
 *            (C) Copyright 2003-2009
 *   Rocco Carbone <rocco /at/ ntop /dot/ org>
 *
 * Released under the terms of GNU General Public License
 * at version 3;  see included COPYING file for details
 *
 * -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 *
 */


/* Operating System header file(s) */
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <sys/utsname.h>


int main (int argc, char * argv [])
{
  int option;
  unsigned char ch;

  char * filename = "etter.finger.os";
  char * name = "fingerprints";
  char * type = "ettercap_t";
  FILE * in = stdin;

  struct utsname host;
  time_t now = time (0);

  /* Notice the program name */
  char * progname = strrchr (argv [0], '/');
  progname = ! progname ? * argv : progname + 1;

#define OPTSTRING "f:n:"
  while ((option = getopt (argc, argv, OPTSTRING)) != EOF)
    {
      switch (option)
        {
        case 'f': filename = optarg; break;
        case 'n': name = optarg; break;
	}
    }

  if (strcmp (filename, "-") && ! (in = fopen (filename, "r")))
    {
      printf ("Error: cannot open %s\n", filename);
      return 0;
    }

  uname (& host);

  printf ("/* \n");
  printf (" * This file was automatically generated by program '%s' from source file '%s'\n", progname, ! strcmp (filename, "-") ? "<stdin>" : filename);
  printf (" * on %s %*.*s\n", host . nodename, 24, 24, ctime (& now));
  printf (" *\n");
  printf (" * The official list is at http://ettercap.cvs.sourceforge.net/ettercap/ettercap_ng/share/etter.finger.os\n");
  printf (" *\n");
  printf (" * (C) Copyright 2003-2009 Rocco Carbone <rocco /at/ ntop /dot/ org>\n");
  printf (" *\n");
  printf (" * Please do not edit\n");
  printf (" */\n");
  printf ("\n");

  printf ("\n");
  printf ("typedef struct\n");
  printf ("{\n");
  printf ("  char * prefix;\n");
  printf ("  char * system;\n");
  printf ("\n");
  printf ("} %s;\n", type);
  printf ("\n");
  printf ("\n");

  printf ("static %s %s [] = \n", type, name);
  printf ("{\n");

  /* Read all lines from the file */
  if (in)
    {
      char line [256];
      char * semicolon;

      while (! feof (in))
	{
	  fgets (line, sizeof (line), in);

	  if (line [strlen (line) - 1] == '\n')
	    line [strlen (line) - 1] = '\0';

	  if (! * line || * line == '#')
	    continue;

	  /* Lookup for the last occurrence of separator into the line */
	  semicolon = strrchr (line, ':');

	  if (semicolon && semicolon - line == 28)
	    printf (" { \"%*.*s\", \"%s\" },\n", 28, 28, line, semicolon + 1);

	}
      fclose (in);
    }

  printf (" {  NULL,                             NULL }\n");
  printf ("};\n\n");

  return 0;
}
