/*
 * oui2c.c - Convert the IEEE 'oui.txt' NIC vendor file
 *           to a C variable to be included in programs
 *
 * -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 *                    _        _
 *              _ __ | | _____| |__
 *             | '_ \| |/ / __| '_ \
 *             | |_) |   <\__ \ | | |
 *             | .__/|_|\_\___/_| |_|
 *             |_|
 *
 *            'pksh', the Packet Shell
 *
 *            (C) Copyright 2003-2009
 *   Rocco Carbone <rocco /at/ ntop /dot/ org>
 *
 * Released under the terms of GNU General Public License
 * at version 3;  see included COPYING file for details
 *
 * -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
 *
 */


/* Operating System header file(s) */
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <time.h>
#include <sys/utsname.h>


int main (int argc, char * argv [])
{
  int option;
  unsigned char ch;

  char * filename = "oui.txt";
  char * name = "vendors";
  char * type = "vendor_t";
  FILE * in = stdin;

  struct utsname host;
  time_t now = time (0);

  /* Notice the program name */
  char * progname = strrchr (argv [0], '/');
  progname = ! progname ? * argv : progname + 1;

#define OPTSTRING "f:n:"
  while ((option = getopt (argc, argv, OPTSTRING)) != EOF)
    {
      switch (option)
        {
        case 'f': filename = optarg; break;
        case 'n': name = optarg; break;
	}
    }

  if (strcmp (filename, "-") && ! (in = fopen (filename, "r")))
    {
      printf ("Error: cannot open %s\n", filename);
      return 0;
    }

  uname (& host);

  printf ("/* \n");
  printf (" * This file was automatically generated by program '%s' from source file '%s'\n", progname, ! strcmp (filename, "-") ? "<stdin>" : filename);
  printf (" * on %s %*.*s\n", host . nodename, 24, 24, ctime (& now));
  printf (" *\n");
  printf (" * The official list is updated daily at http://standards.ieee.org/regauth/oui/oui.txt\n");
  printf (" *\n");
  printf (" * (C) Copyright 2003-2009 Rocco Carbone <rocco /at/ ntop /dot/ org>\n");
  printf (" *\n");
  printf (" * Please do not edit\n");
  printf (" */\n");
  printf ("\n");

  printf ("\n");
  printf ("typedef struct\n");
  printf ("{\n");
  printf ("  char * prefix;\n");
  printf ("  char * vendor;\n");
  printf ("\n");
  printf ("} %s;\n", type);
  printf ("\n");
  printf ("\n");

  printf ("static %s %s [] = \n", type, name);
  printf ("{\n");

  /* Read all lines from the file */
  if (in)
    {
      char line [1024];
      char vendor [1024];
      char t1 [1024];
      char t2 [1024];
      char a, b, c, d, e, f;
      char * v;

      while (! feof (in))
	{
	  fgets (line, sizeof (line), in);

	  if (sscanf (line, "%c%c-%c%c-%c%c%[^(](hex)%[^(0-9A-Za-z)]%[^\n]", & a, & b, & c, & d, & e, & f, t1, t2, vendor) != 9)
	    continue;

	  sprintf (t1, "%c%c:%c%c:%c%c", tolower (a), tolower (b), tolower (c), tolower (d), tolower (e), tolower (f));

	  v = vendor;
	  while (* v)
	    if (* v ++ == '"')
	      * -- v = '\'';

	  printf (" { \"%s\", \"%s\" },\n", t1, vendor);
	}
      fclose (in);
    }

  printf (" {  NULL,       NULL }\n");
  printf ("};\n\n");

  return 0;
}
